controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    mecDrive_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mecDrive_controller:
  ros__parameters:
    reference_timeout: 0.9

    front_left_wheel_command_joint_name: "front_left_joint"
    front_right_wheel_command_joint_name: "front_right_joint"
    rear_right_wheel_command_joint_name: "rear_right_joint"
    rear_left_wheel_command_joint_name: "rear_left_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.1
      sum_of_robot_center_projection_on_X_Y_axis: 1.0

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_joint
      - front_right_joint
      - rear_left_joint
      - rear_right_joint
