controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    tricycle_controller:
      type: tricycle_controller/TricycleController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

tricycle_controller:
  ros__parameters:
    traction_joint_name: front_joint
    steering_joint_name: chassis_to_front_steering
    wheel_radius: 0.1
    wheelbase: 0.5
    enable_odom_tf: true
    use_sim_time: true
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    odom_only_twist: true
    publish_ackermann_command: true
    traction:
      max_acceleration: 1.0
      max_deceleration: 1.0
    steering:
      max_position: 0.785 # pi/4
      max_velocity: 1.0

joint_state_broadcaster:
  ros__parameters:
    joints:
      - chassis_to_front_steering
      - front_joint
      - rear_left_joint
      - rear_right_joint
