"""Final Check wizard page — displays the generated URDF for review and manual editing."""

import os
from PyQt5.QtWidgets import (
    QWizardPage, QVBoxLayout, QHBoxLayout, QTextEdit, QLabel,
    QPushButton, QApplication, QFileDialog, QMessageBox, QSizePolicy,
)
from PyQt5.QtGui import QFont
from PyQt5.QtCore import Qt


class FinalCheckPage(QWizardPage):
    def __init__(self, urdf_manager, parent=None):
        super().__init__(parent)
        self.urdf_manager = urdf_manager
        self._base_text = ""   # last text loaded from generator (used by Revert)

        self.setTitle("Final Check — Review & Edit Generated URDF")
        self.setSubTitle(
            "You can edit the URDF directly below. "
            "Click Revert Changes to undo manual edits. "
            "Click Refresh to reload the latest generated output."
        )

        layout = QVBoxLayout(self)
        layout.setContentsMargins(14, 8, 14, 10)
        layout.setSpacing(8)

        # ── Toolbar row ──────────────────────────────────────────────────────
        toolbar = QHBoxLayout()
        toolbar.setSpacing(8)

        self._status = QLabel("")
        self._status.setStyleSheet("font-size: 9pt; color: #7F8C8D;")
        toolbar.addWidget(self._status, 1)

        refresh_btn = QPushButton("⟳  Refresh")
        refresh_btn.setMinimumHeight(34)
        refresh_btn.setMinimumWidth(100)
        refresh_btn.setToolTip("Reload the URDF generated by Configure Parameters")
        refresh_btn.clicked.connect(self._refresh)
        toolbar.addWidget(refresh_btn)

        revert_btn = QPushButton("↺  Revert Changes")
        revert_btn.setMinimumHeight(34)
        revert_btn.setMinimumWidth(140)
        revert_btn.setToolTip("Discard manual edits and restore the last generated URDF")
        revert_btn.clicked.connect(self._revert)
        toolbar.addWidget(revert_btn)

        copy_btn = QPushButton("Copy to Clipboard")
        copy_btn.setMinimumHeight(34)
        copy_btn.setMinimumWidth(150)
        copy_btn.clicked.connect(self._copy)
        toolbar.addWidget(copy_btn)

        save_btn = QPushButton("Save URDF")
        save_btn.setMinimumHeight(34)
        save_btn.setMinimumWidth(100)
        save_btn.clicked.connect(self._save)
        toolbar.addWidget(save_btn)

        layout.addLayout(toolbar)

        # ── URDF editor ──────────────────────────────────────────────────────
        self._text = QTextEdit()
        self._text.setReadOnly(False)   # editable
        self._text.setLineWrapMode(QTextEdit.NoWrap)
        self._text.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self._text.setFont(QFont("Monospace", 10))
        self._text.setStyleSheet("""
            QTextEdit {
                background-color: #1E1E1E;
                color: #D4D4D4;
                border: 1px solid #555;
                border-radius: 4px;
                padding: 6px;
            }
        """)
        layout.addWidget(self._text, 1)

    # ── Wizard page lifecycle ────────────────────────────────────────────────

    def initializePage(self):
        self._refresh()

    # ── Actions ──────────────────────────────────────────────────────────────

    def _refresh(self):
        """Reload from the generator and reset the revert baseline."""
        urdf = self.urdf_manager.get_urdf_text() or ""
        self._base_text = urdf
        self._text.setPlainText(urdf)
        self._update_status(urdf)

    def _revert(self):
        """Restore the last text loaded from the generator (discard manual edits)."""
        self._text.setPlainText(self._base_text)
        self._update_status(self._base_text)

    def _update_status(self, urdf: str):
        if not urdf or urdf.startswith("Error"):
            self._status.setText(
                "No URDF generated yet — go back to Configure Parameters and click Apply."
            )
            self._status.setStyleSheet("font-size: 9pt; color: #E74C3C;")
            return

        lines = urdf.count('\n') + 1
        links = urdf.count('<link ')
        joints = urdf.count('<joint ')
        rt = self.urdf_manager.last_robot_type or '—'
        ct = self.urdf_manager.last_controller_type or '—'
        self._status.setText(
            f"Robot: {rt}   Controller: {ct}   "
            f"{lines} lines  ·  {links} links  ·  {joints} joints"
        )
        self._status.setStyleSheet("font-size: 9pt; color: #7F8C8D;")

    def _copy(self):
        text = self._text.toPlainText()
        if text:
            QApplication.clipboard().setText(text)

    def _save(self):
        urdf = self._text.toPlainText()
        if not urdf or urdf.startswith("Error"):
            QMessageBox.warning(
                self, "No URDF",
                "Generate a URDF first by clicking Apply on the Configure Parameters page."
            )
            return

        path, _ = QFileDialog.getSaveFileName(
            self, "Save URDF", os.path.expanduser("~/robot.urdf"), "URDF Files (*.urdf)"
        )
        if path:
            try:
                with open(path, "w") as f:
                    f.write(urdf)
            except OSError as e:
                QMessageBox.critical(self, "Save Failed", str(e))
