controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    triSteer_controller:
      type: tricycle_steering_controller/TricycleSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

triSteer_controller:
  ros__parameters:
    reference_timeout: 2.0
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    traction_joints_names: [rear_left_joint, rear_right_joint]
    steering_joints_names: [chassis_to_front_steering]

    wheelbase: 0.5
    wheel_track: 0.4
    traction_wheels_radius: 0.1

joint_state_broadcaster:
  ros__parameters:
    joints:
      - chassis_to_front_steering
      - front_joint
      - rear_left_joint
      - rear_right_joint
